### ISSUE TITLE
Was the recent publish of the gem version 2.0.1 deliberate?

### ISSUE THREAD

**Issue by shepmaster** [deckar01/task_list#22]
The gem was pushed to [Rubygems a few days ago](https://rubygems.org/gems/deckar01-task_list) (2018-01-11), but there haven't been any changes to the repository's default branch since April of 2018.

Was this publish deliberate, or is something nefarious happening?

**Comment by deckar01** [comment]
The 2.0.1 release was javascript patch, and only the npm package got released at the time. Someone pointed it out recently and requested a gem release. Sorry for the delay.

**Comment by deckar01** [comment]
I the future you can audit the contents of a gem by fetching and diffing it with the previous version.

```sh
gem fetch deckar01-task_list -v 2.0.0
gem fetch deckar01-task_list -v 2.0.1
gem unpack deckar01-task_list-2.0.0.gem
gem unpack deckar01-task_list-2.0.1.gem
diff -u deckar01-task_list-2.0.0/ deckar01-task_list-2.0.1/
```

```diff
diff -u deckar01-task_list-2.0.0/.travis.yml deckar01-task_list-2.0.1/.travis.yml
--- deckar01-task_list-2.0.0/.travis.yml	2019-01-14 11:15:52.000000000 -0600
+++ deckar01-task_list-2.0.1/.travis.yml	2019-01-14 11:16:02.000000000 -0600
@@ -5,7 +5,6 @@
   - ./script/bootstrap
 script: ./script/cibuild
 rvm:
-  - 1.9.3
   - 2.0
   - 2.1
   - 2.2
Common subdirectories: deckar01-task_list-2.0.0/app and deckar01-task_list-2.0.1/app
diff -u deckar01-task_list-2.0.0/bower.json deckar01-task_list-2.0.1/bower.json
--- deckar01-task_list-2.0.0/bower.json	2019-01-14 11:15:52.000000000 -0600
+++ deckar01-task_list-2.0.1/bower.json	2019-01-14 11:16:02.000000000 -0600
@@ -1,6 +1,6 @@
 {
   "name": "deckar01-task_list",
-  "version": "2.0.0",
+  "version": "2.0.1",
   "description": "Markdown TaskList components",
   "homepage": "https://github.com/deckar01/task_list",
   "devDependencies": {
Common subdirectories: deckar01-task_list-2.0.0/dist and deckar01-task_list-2.0.1/dist
Common subdirectories: deckar01-task_list-2.0.0/lib and deckar01-task_list-2.0.1/lib
diff -u deckar01-task_list-2.0.0/package.json deckar01-task_list-2.0.1/package.json
--- deckar01-task_list-2.0.0/package.json	2019-01-14 11:15:52.000000000 -0600
+++ deckar01-task_list-2.0.1/package.json	2019-01-14 11:16:02.000000000 -0600
@@ -1,6 +1,6 @@
 {
   "name": "deckar01-task_list",
-  "version": "2.0.0",
+  "version": "2.0.1",
   "description": "Markdown TaskList components",
   "main": "dist/task_list.js",
   "directories": {
Common subdirectories: deckar01-task_list-2.0.0/script and deckar01-task_list-2.0.1/script
diff -u deckar01-task_list-2.0.0/task_list.gemspec deckar01-task_list-2.0.1/task_list.gemspec
--- deckar01-task_list-2.0.0/task_list.gemspec	2019-01-14 11:15:52.000000000 -0600
+++ deckar01-task_list-2.0.1/task_list.gemspec	2019-01-14 11:16:02.000000000 -0600
@@ -16,13 +16,13 @@
   gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
   gem.require_paths = ["lib"]
 
-  gem.required_ruby_version = ">= 2.1.0"
+  gem.required_ruby_version = ">= 2.0.0"
 
   gem.add_dependency "activesupport", "~> 4.0" if RUBY_VERSION < '2.2.2'
   gem.add_dependency "nokogiri", "~> 1.6.0" if RUBY_VERSION < '2.1.0'
   gem.add_dependency "html-pipeline"
 
-  gem.add_development_dependency "github-markdown"
+  gem.add_development_dependency "commonmarker"
   gem.add_development_dependency "rake"
   gem.add_development_dependency "coffee-script"
   gem.add_development_dependency "json"
Common subdirectories: deckar01-task_list-2.0.0/test and deckar01-task_list-2.0.1/test
```

The only actual change is replacing the deprecated `github-markdown` dev dependency with `commonmarker`.

If you know of a better way to automate this that would be great.

**Comment by shepmaster** [comment]
> a better way to audit gem updates

We use dependabot, which scrapes gem release notes, CHANGELOG files, and shows the difference between tagged releases. Unfortunately, this library doesn't seem to use any of those mechanisms. Barring that, I'd look to find the commits that changed the gem version and diff them (https://github.com/deckar01/task_list/compare/bce1c5e1f9f4e85bb8ac8c07bd468343655c8e5d...ba9a48994f7dd1fa30bdd66bdd35608ec1cf8a56).

This isn't *really* an audit of the gem, as I'm trusting that what went to rubygems matches what's in your git repo, but I'm not currently interested in auditing for actively malicious gem authors, just simple mistakes or changes that might break our usage. Downloading the gem is the only "true" audit, AFAIK. 

The real concern isn't the diff, just the large time difference between the change to the code and the publish of the gem, which was surprising.

**Comment by shepmaster** [comment]
Thanks for the responses and for the gem!
