### ISSUE TITLE
Phantom Tests Not Running

### ISSUE THREAD

**Issue by deckar01** [deckar01/task_list#28]
The setup for the phantom tests is extremely fragile. The server starts, waits 3 seconds, and assumes the tests finished then exits. It does not appear to actually be running the js tests.

**Comment by digitalmoksha** [comment]
I don't know much about the JS testing frameworks, but if it's any help, GitLab has [started migrating](https://docs.gitlab.com/ee/development/testing_guide/frontend_testing.html#jest) to using [Jest](https://jestjs.io)

**Comment by deckar01** [comment]
I got it working by swapping PhantomJS out for Karma + Chrome Headless. I also used the webpack plugin for karma to compile the coffeescript on the fly instead of serving it with rackup.
It should at least error if the tests stop working now.  #29

**Comment by digitalmoksha** [comment]
👍
